### PR TITLE
base64 error logging

### PR DESCRIPTION
**Pull request by DreRandaci**

### CODE REVIEW

**Comment by DreRandaci** [comment]
@morecallan @zoeames @rousell https://angular-contacts-ff671.firebaseapp.com/

**Comment by DreRandaci** [comment]
@morecallan check this https://angular-contacts-ff671.firebaseapp.com

**Comment by morecallan** [comment]
@DreRandaci - make sure you do the update to the createContactObject function to address when picInfo isn't send in.

**Comment by DreRandaci** [comment]
@morecallan ahh forgot about that, it's changed

**Pull request merged**
